### ISSUE TITLE
Required / optional fields structure

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern-curated-plugins-list#4]
**Current situation**
(updated as we confirm/deny the structure)

```
name
latest
  version
  downloadUrlZip
legacy
  {semver}
      version
      downloadUrlZip
```

**Required field proposals**

TBA

**Optional field proposals**

Inside `latest` and `{semver}` blocks:
- [ ] `help` (link to readme/docs site)
- [ ] `require:`
`  min` {txpsemver}
`  max` {txpsemver}

Also of interest:
1. Are we going camelCase or snake_case for keys?
2. ...

**Comment by petecooper** [comment]
`license` in some format, either a link to the `LICENSE` file or from an agreed list.

**Comment by philwareham** [comment]
Let's not get too bogged down in superfluous data please. The sole purpose of these JSON files (in my opinion) is to track version numbers and download endpoints for a plugin so that:

1. The plugin site, and hopefully in future Textpattern itself, knows the latest version of a plugin (and legacy version of plugin for older Textpattern versions)
2. The plugin site, and hopefully in future Textpattern itself, knows where to download the plugin from.

Most other data will be held on the plugins site itself. I agree that there could be two download links (one a zip download of the PHP for flat file or auto-install situations, one a txt download for the legacy way people install plugins into the control panel via copy/paste.

The more we introduce here the harder it is to keep the data up to date.

So... I don't think we need:

```
summary
author (name)
authorUrl (link to site)
license (link or text or option list?)
```

Others we can discuss and agree upon.

**Comment by Bloke** [comment]
I can't think of any more stuff to add that would allow an automated process or human to make an informed decision on whether to proceed with an update or not.

The Txp Plugins panel (or other endpoint) can query the file and establish if it meets min/max upgrade requirements. It can present the new version number to the administrator and offer a link to the help docs so they can choose whether to go ahead or not (i.e. follow the zip download link to obtain the .txt file).

The only thing missing is a link to the complete plugin endpoint - a page on the eventual repo site, or author's own site/VCS repo). But, if we decide to enforce this site as a first-point-of-contact and it's going to use a known-format for plugins (e.g. plugins.textpattern.com/abc_plugin, which may have a regex-based redirect to the actual plugin page, in whatever section we put them in) then we don't really need that.

One more thing, possibly tangential. When we say `downloadUrlZip` are we referring to:

1. The .txt file, which is gzipped behind the BASE64 blob (as opposed to an uncompressed .txt file).
2. A zipped plugin bundle, which may contain a bunch of resources alongside the .txt file that get installed in the texpattern/plugins dir.
3. Both.

**Comment by petecooper** [comment]
>When we say downloadUrlZip are we referring to:

For me, 2. The author makes a release, the release contains files, we point to the release, that handles the heavy lifting…or am I missing the point? Honest question.

**Comment by philwareham** [comment]
In terms of the pages on the plugins website, they will always follow this URL pattern:

    https://plugins.textpattern.com/plugins/abc_plugin

For example: https://plugins.textpattern.com/plugins/com_connect

**Comment by Bloke** [comment]
> The author makes a release, the release contains files, we point to the release, that handles the heavy lifting…

Yeah, that's fine. I didn't explain it well, sorry.

Txp can handle both - either browse for zip file or paste .txt file contents into the textarea. I was just curious whether the 'Zip' part of the JSON key was intended to refer to the file extension that we intend to link to, or the gzipped nature of the .txt file. Or whether it didn't matter.

In reality we can link to either and it won't matter too much (as long as we detect which type it is and either unzip + install files in the /plugins directory, or just `install()` the .txt file). I was more questioning the name of the JSON key. As in, if we decide at a later stage to differentiate between types of plugin download, how do we name them?

* `downloadUrlUncompressed` for old-skool .txt files that aren't gzipped inside the BASE64 blob?
* `downloadUrlXZip` for .tar.xz files?
* `downloadUrlGZip` for .tar.gz files?
* ...

My point is, if we name the JSON key to more closely resemble the _type_ of download available,
would anyone take up the system to offer an uncompressed.txt file, a compressed .txt file, and a .zip package? Or can we get away with just `downloadUrl` and they have to pick one?

I'm not even sure if uncompressed plugins are needed any more. We still support them but the only reason we had them was because some hosts didn't have the zip compression libraries installed. Not sure that's still the case, but I guess there must be some out there that don't have them.

**Comment by Bloke** [comment]
One other thing, while I think about it: beta versions.

How do we anticipate handling those? A dedicated block in the JSON file? If so, do we notify that a beta is available? e.g. via an option in Txp; maybe a checkbox on the Plugins panel that says "Include betas?" or something?

If so we need to know that the beta is "greater than" the version in the `latest` block. Can't rely on the position of the block in the file. Do we permit a dedicated `beta` block? Or do we prefer a 'betaDownload' link in the `latest` block?

Throw ideas out and we'll figure which is best.

**Comment by philwareham** [comment]
Back into this now. I have added a `beta` block into the example in the repo. That would be optional and also would be overrode by `stable` if the stable version was higher than the beta version's semver.

I'm trying to figure out the best way to do the download URL endpoints. I'm thinking something like:

    "downloadUrlPhp":

Which points to a zip download that can be imported into Textpattern via the more modern `plugins` directory option. And:

    "downloadUrlTxt":

Which points to a download that contains the older `txt` style file and/or zipped variant thereof.

Is that enough, and viable?

We have to assume that sometimes only one of the above options is available I guess. (i.e. a `txt` file is available but no source code (PHP), or source code is available but the author has not done a compiled `txt` file.

**Comment by Bloke** [comment]
That sounds perfectly workable. Perhaps in the next core version we allow all plugin types to be uploaded via the browse... feature. And I'd like to show a preview for all content types, ideally, so that if anyone installs a plugin direct from an endpoint - be it github or via the plugins site - they have visibility of what's going to be installed. I think that's important for trust. If we can build in the option to opt in/out of various chunks during the verify step, even better.

**Comment by philwareham** [comment]
I'm happy with the structure of this JSON file now. So closing this issue.
