### ISSUE TITLE
Consider a JSON linter as part of CI/CD pipeline

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern-curated-plugins-list#8]
As title, we should consider a linter on new/existing JSON stubs, perhaps as a part of CI/CD.

**Comment by petecooper** [comment]
@philwareham - I see `jsonlint` stuff, perfect. Let me know when you're happy and I'll try a slightly malformed JSON to test.

**Comment by philwareham** [comment]
OK, just linking a CI to it and I'll let you know shortly when to try and break it!

**Comment by petecooper** [comment]
Possibly for another issue - check for required JSON nodes in CI, too.

**Comment by philwareham** [comment]
Not sure I can work out how to check for required nodes. Someone with better JS chops than me might be able to do a script for that. In the meantime, please create a slightly mangled JSON file and let's see if the CI works.

**Comment by philwareham** [comment]
OK, I've got CI worming now and it's correctly reporting the bad JSON file. If you can now fix and we should get a successful build again.

**Comment by petecooper** [comment]
@philwareham - safe to close this?

**Comment by philwareham** [comment]
Well, unless @bloke or @bloatware want to write a JS script that checks for required entries - then yes I'm happy to close. We will verify manually any new cards anyway so the linter was just a safeguard against malformed JSON files.
